export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED';
export const FORGOT_PASSWORD_CLEAR = 'FORGOT_PASSWORD_CLEAR';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAILED = 'USER_LIST_FAILED';

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED';

export const CREATE_PASSWORD_REQUEST = 'CREATE_PASSWORD_REQUEST';
export const CREATE_PASSWORD_SUCCESS = 'CREATE_PASSWORD_SUCCESS';
export const CREATE_PASSWORD_FAILED = 'CREATE_PASSWORD_FAILED';

export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAILED = 'CATEGORY_LIST_FAILED';
export const CATEGORY_LIST_CLEAR = 'CATEGORY_LIST_CLEAR';

//contect setup step seven
export const CONTECT_SETUP_REQUEST = 'CONTECT_SETUP_REQUEST';
export const CONTECT_SETUP_SUCCESS = 'CONTECT_SETUP_SUCCESS';
export const CONTECT_SETUP_FAILED = 'CONTECT_SETUP_FAILED';
export const CONTECT_SETUP_CLEAR = 'CONTECT_SETUP_CLEAR';
//term of payment setup step eight
export const TERM_OF_PAYMENT_SETUP_REQUEST = 'TERM_OF_PAYMENT_SETUP_REQUEST';
export const TERM_OF_PAYMENT_SETUP_SUCCESS = 'TERM_OF_PAYMENT_SETUP_SUCCESS';
export const TERM_OF_PAYMENT_SETUP_FAILED = 'TERM_OF_PAYMENT_SETUP_FAILED';
export const TERM_OF_PAYMENT_SETUP_CLEAR = 'TERM_OF_PAYMENT_SETUP_CLEAR';
//addintional info
export const ADDITIONAL_INFO_REQUEST = 'ADDITIONAL_INFO_REQUEST';
export const ADDITIONAL_INFO_SUCCESS = 'ADDITIONAL_INFO_SUCCESS';
export const ADDITIONAL_INFO_FAILED = 'ADDITIONAL_INFO_FAILED';
export const ADDITIONAL_INFO_CLEAR = 'ADDITIONAL_INFO_CLEAR';

export const SET_NAVIGATION_VALUE = 'SET_NAVIGATION_VALUE';
export const SET_ONBOARDING_VALUE = 'SET_ONBOARDING_VALUE';

// Booking Actions  (Debashish Gopw)
export const UPCOMING_BOOKING_LIST_REQUEST = 'UPCOMING_BOOKING_LIST_REQUEST';
export const UPCOMING_BOOKING_LIST_SUCCESS = 'UPCOMING_BOOKING_LIST_SUCCESS';
export const UPCOMING_BOOKING_LIST_FAILED = 'UPCOMING_BOOKING_LIST_FAILED';
export const UPCOMING_BOOKING_LIST_CLEAR = 'UPCOMING_BOOKING_LIST_CLEAR';

export const PREVIOUS_BOOKING_LIST_REQUEST = 'PREVIOUS_BOOKING_LIST_REQUEST';
export const PREVIOUS_BOOKING_LIST_SUCCESS = 'PREVIOUS_BOOKING_LIST_SUCCESS';
export const PREVIOUS_BOOKING_LIST_FAILED = 'PREVIOUS_BOOKING_LIST_FAILED';
export const PREVIOUS_BOOKING_LIST_CLEAR = 'PREVIOUS_BOOKING_LIST_CLEAR';

export const ACCEPT_TERMS_CONDITION_REQUEST = 'ACCEPT_TERMS_CONDITION_REQUEST';
export const ACCEPT_TERMS_CONDITION_SUCCESS = 'ACCEPT_TERMS_CONDITION_SUCCESS';
export const ACCEPT_TERMS_CONDITION_FAILED = 'ACCEPT_TERMS_CONDITION_FAILED';
export const ACCEPT_TERMS_CONDITION_CLEAR = 'ACCEPT_TERMS_CONDITION_CLEAR';

export const CMS_PAGE_REQUEST = 'CMS_PAGE_REQUEST';
export const CMS_PAGE_SUCCESS = 'CMS_PAGE_SUCCESS';
export const CMS_PAGE_FAILED = 'CMS_PAGE_FAILED';
export const CMS_PAGE_CLEAR = 'CMS_PAGE_CLEAR';

export const FAQ_LISTING_REQUEST = 'FAQ_LISTING_REQUEST';
export const FAQ_LISTING_SUCCESS = 'FAQ_LISTING_SUCCESS';
export const FAQ_LISTING_FAILED = 'FAQ_LISTING_FAILED';
export const FAQ_LISTING_CLEAR = 'FAQ_LISTING_CLEAR';

// Profile Actions (Debashish Gope)
export const PROFILE_VIEW_REQUEST = 'PROFILE_VIEW_REQUEST';
export const PROFILE_VIEW_SUCCESS = 'PROFILE_VIEW_SUCCESS';
export const PROFILE_VIEW_FAILED = 'PROFILE_VIEW_FAILED';
export const PROFILE_VIEW_CLEAR = 'PROFILE_VIEW_CLEAR';

export const PROFIL_IMG_UPDATE_REQUEST = 'PROFIL_IMG_UPDATE_REQUEST';
export const PROFIL_IMG_UPDATE_SUCCESS = 'PROFIL_IMG_UPDATE_SUCCESS';
export const PROFIL_IMG_UPDATE_FAILED = 'PROFIL_IMG_UPDATE_FAILED';
export const PROFIL_IMG_UPDATE_CLEAR = 'PROFIL_IMG_UPDATE_CLEAR';

export const CHANGE_NAME_REQUEST = 'CHANGE_NAME_REQUEST';
export const CHANGE_NAME_SUCCESS = 'CHANGE_NAME_SUCCESS';
export const CHANGE_NAME_FAILED = 'CHANGE_NAME_FAILED';
export const CHANGE_NAME_CLEAR = 'CHANGE_NAME_CLEAR';

export const CHANGE_EMAIL_REQUEST = 'CHANGE_EMAIL_REQUEST';
export const CHANGE_EMAIL_SUCCESS = 'CHANGE_EMAIL_SUCCESS';
export const CHANGE_EMAIL_FAILED = 'CHANGE_EMAIL_FAILED';
export const CHANGE_EMAIL_CLEAR = 'CHANGE_EMAIL_CLEAR';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';
export const CHANGE_PASSWORD_CLEAR = 'CHANGE_PASSWORD_CLEAR';

export const CHANGE_PHONE_NUMBER_REQUEST = 'CHANGE_PHONE_NUMBER_REQUEST';
export const CHANGE_PHONE_NUMBER_SUCCESS = 'CHANGE_PHONE_NUMBER_SUCCESS';
export const CHANGE_PHONE_NUMBER_FAILED = 'CHANGE_PHONE_NUMBER_FAILED';
export const CHANGE_PHONE_NUMBER_CLEAR = 'CHANGE_PHONE_NUMBER_CLEAR';

export const SEND_OTP_REQUEST = 'SEND_OTP_REQUEST';
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS';
export const SEND_OTP_FAILED = 'SEND_OTP_FAILED';
export const SEND_OTP_CLEAR = 'SEND_OTP_CLEAR';

export const CUSTOMER_LOGOUT_REQUEST = 'CUSTOMER_LOGOUT_REQUEST';
export const CUSTOMER_LOGOUT_SUCCESS = 'CUSTOMER_LOGOUT_SUCCESS';
export const CUSTOMER_LOGOUT_FAILED = 'CUSTOMER_LOGOUT_FAILED';
export const CUSTOMER_LOGOUT_CLEAR = 'CUSTOMER_LOGOUT_CLEAR';

export const LIST_CARD_REQUEST = 'LIST_CARD_REQUEST';
export const LIST_CARD_SUCCESS = 'LIST_CARD_SUCCESS';
export const LIST_CARD_FAILED = 'LIST_CARD_FAILED';
export const LIST_CARD_CLEAR = 'LIST_CARD_CLEAR';

export const ADD_CARD_REQUEST = 'ADD_CARD_REQUEST';
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS';
export const ADD_CARD_FAILED = 'ADD_CARD_FAILED';
export const ADD_CARD_CLEAR = 'ADD_CARD_CLEAR';

export const UPDATE_CARD_REQUEST = 'UPDATE_CARD_REQUEST';
export const UPDATE_CARD_SUCCESS = 'UPDATE_CARD_SUCCESS';
export const UPDATE_CARD_FAILED = 'UPDATE_CARD_FAILED';
export const UPDATE_CARD_CLEAR = 'UPDATE_CARD_CLEAR';

export const DELETE_CARD_REQUEST = 'DELETE_CARD_REQUEST';
export const DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS';
export const DELETE_CARD_FAILED = 'DELETE_CARD_FAILED';
export const DELETE_CARD_CLEAR = 'DELETE_CARD_CLEAR';

export const ALL_NOTIFICATION_REQUEST = 'ALL_NOTIFICATION_REQUEST';
export const ALL_NOTIFICATION_SUCCESS = 'ALL_NOTIFICATION_SUCCESS';
export const ALL_NOTIFICATION_FAILED = 'ALL_NOTIFICATION_FAILED';
export const ALL_NOTIFICATION_CLEAR = 'ALL_NOTIFICATION_CLEAR';

export const PROMO_NOTIFICATION_REQUEST = 'PROMO_NOTIFICATION_REQUEST';
export const PROMO_NOTIFICATION_SUCCESS = 'PROMO_NOTIFICATION_SUCCESS';
export const PROMO_NOTIFICATION_FAILED = 'PROMO_NOTIFICATION_FAILED';
export const PROMO_NOTIFICATION_CLEAR = 'PROMO_NOTIFICATION_CLEAR';

export const PROS_NOTIFICATION_REQUEST = 'PROS_NOTIFICATION_REQUEST';
export const PROS_NOTIFICATION_SUCCESS = 'PROS_NOTIFICATION_SUCCESS';
export const PROS_NOTIFICATION_FAILED = 'PROS_NOTIFICATION_FAILED';
export const PROS_NOTIFICATION_CLEAR = 'PROS_NOTIFICATION_CLEAR';

export const BOOKING_REMINDER_REQUEST = 'BOOKING_REMINDER_REQUEST';
export const BOOKING_REMINDER_SUCCESS = 'BOOKING_REMINDER_SUCCESS';
export const BOOKING_REMINDER_FAILED = 'BOOKING_REMINDER_FAILED';
export const BOOKING_REMINDER_CLEAR = 'BOOKING_REMINDER_CLEAR';

export const PROFESSIONAL_FAQ_LISTING_REQUEST =
  'PROFESSIONAL_FAQ_LISTING_REQUEST';
export const PROFESSIONAL_FAQ_LISTING_SUCCESS =
  'PROFESSIONAL_FAQ_LISTING_SUCCESS';
export const PROFESSIONAL_FAQ_LISTING_FAILED =
  'PROFESSIONAL_FAQ_LISTING_FAILED';
export const PROFESSIONAL_FAQ_LISTING_CLEAR = 'PROFESSIONAL_FAQ_LISTING_CLEAR';

export const PROFESSIONAL_FAQ_ADD_REQUEST = 'PROFESSIONAL_FAQ_ADD_REQUEST';
export const PROFESSIONAL_FAQ_ADD_SUCCESS = 'PROFESSIONAL_FAQ_ADD_SUCCESS';
export const PROFESSIONAL_FAQ_ADD_FAILED = 'PROFESSIONAL_FAQ_ADD_FAILED';
export const PROFESSIONAL_FAQ_ADD_CLEAR = 'PROFESSIONAL_FAQ_ADD_CLEAR';

export const PROFESSIONAL_FAQ_EDIT_REQUEST = 'PROFESSIONAL_FAQ_EDIT_REQUEST';
export const PROFESSIONAL_FAQ_EDIT_SUCCESS = 'PROFESSIONAL_FAQ_EDIT_SUCCESS';
export const PROFESSIONAL_FAQ_EDIT_FAILED = 'PROFESSIONAL_FAQ_EDIT_FAILED';
export const PROFESSIONAL_FAQ_EDIT_CLEAR = 'PROFESSIONAL_FAQ_EDIT_CLEAR';

export const MAIN_CATEGORY_VIEW_REQUEST = 'MAIN_CATEGORY_VIEW_REQUEST';
export const MAIN_CATEGORY_VIEW_SUCCESS = 'MAIN_CATEGORY_VIEW_SUCCESS';
export const MAIN_CATEGORY_VIEW_FAILED = 'MAIN_CATEGORY_VIEW_FAILED';
export const MAIN_CATEGORY_VIEW_CLEAR = 'MAIN_CATEGORY_VIEW_CLEAR';

export const MAIN_CATEGORY_EDIT_REQUEST = 'MAIN_CATEGORY_EDIT_REQUEST';
export const MAIN_CATEGORY_EDIT_SUCCESS = 'MAIN_CATEGORY_EDIT_SUCCESS';
export const MAIN_CATEGORY_EDIT_FAILED = 'MAIN_CATEGORY_EDIT_FAILED';
export const MAIN_CATEGORY_EDIT_CLEAR = 'MAIN_CATEGORY_EDIT_CLEAR';

export const ADDITIONAL_CATEGORY_VIEW_REQUEST =
  'ADDITIONAL_CATEGORY_VIEW_REQUEST';
export const ADDITIONAL_CATEGORY_VIEW_SUCCESS =
  'ADDITIONAL_CATEGORY_VIEW_SUCCESS';
export const ADDITIONAL_CATEGORY_VIEW_FAILED =
  'ADDITIONAL_CATEGORY_VIEW_FAILED';
export const ADDITIONAL_CATEGORY_VIEW_CLEAR = 'ADDITIONAL_CATEGORY_VIEW_CLEAR';

export const VERIFY_IDENTITY_REQUEST = 'VERIFY_IDENTITY_REQUEST';
export const VERIFY_IDENTITY_SUCCESS = 'VERIFY_IDENTITY_SUCCESS';
export const VERIFY_IDENTITY_FAILED = 'VERIFY_IDENTITY_FAILED';
export const VERIFY_IDENTITY_CLEAR = 'VERIFY_IDENTITY_CLEAR';

export const PENDING_VERIFICATION_REQUEST = 'PENDING_VERIFICATION_REQUEST';
export const PENDING_VERIFICATION_SUCCESS = 'PENDING_VERIFICATION_SUCCESS';
export const PENDING_VERIFICATION_FAILED = 'PENDING_VERIFICATION_FAILED';
export const PENDING_VERIFICATION_CLEAR = 'PENDING_VERIFICATION_CLEAR';

export const PROF_UPCOMING_BOOKING_REQUEST = 'PROF_UPCOMING_BOOKING_REQUEST';
export const PROF_UPCOMING_BOOKING_SUCCESS = 'PROF_UPCOMING_BOOKING_SUCCESS';
export const PROF_UPCOMING_BOOKING_FAILED = 'PROF_UPCOMING_BOOKING_FAILED';
export const PROF_UPCOMING_BOOKING_CLEAR = 'PROF_UPCOMING_BOOKING_CLEAR';

export const PRO_BOOKING_INNER_REQUEST = 'PRO_BOOKING_INNER_REQUEST';
export const PRO_BOOKING_INNER_SUCCESS = 'PRO_BOOKING_INNER_SUCCESS';
export const PRO_BOOKING_INNER_FAILED = 'PRO_BOOKING_INNER_FAILED';
export const PRO_BOOKING_INNER_CLEAR = 'PRO_BOOKING_INNER_CLEAR';

export const PRO_BOOKING_CANCEL_REQUEST = 'PRO_BOOKING_CANCEL_REQUEST';
export const PRO_BOOKING_CANCEL_SUCCESS = 'PRO_BOOKING_CANCEL_SUCCESS';
export const PRO_BOOKING_CANCEL_FAILED = 'PRO_BOOKING_CANCEL_FAILED';
export const PRO_BOOKING_CANCEL_CLEAR = 'PRO_BOOKING_CANCEL_CLEAR';

export const PRO_BOOKING_NOSHOW_REQUEST = 'PRO_BOOKING_NOSHOW_REQUEST';
export const PRO_BOOKING_NOSHOW_SUCCESS = 'PRO_BOOKING_NOSHOW_SUCCESS';
export const PRO_BOOKING_NOSHOW_FAILED = 'PRO_BOOKING_NOSHOW_FAILED';
export const PRO_BOOKING_NOSHOW_CLEAR = 'PRO_BOOKING_NOSHOW_CLEAR';

export const PRO_BOOKING_NOTES_Add_REQUEST = 'PRO_BOOKING_NOTES_Add_REQUEST';
export const PRO_BOOKING_NOTES_Add_SUCCESS = 'PRO_BOOKING_NOTES_Add_SUCCESS';
export const PRO_BOOKING_NOTES_Add_FAILED = 'PRO_BOOKING_NOTES_Add_FAILED';
export const PRO_BOOKING_NOTES_Add_CLEAR = 'PRO_BOOKING_NOTES_Add_CLEAR';

export const PRO_BOOKING_COMPLETE_REQUEST = 'PRO_BOOKING_COMPLETE_REQUEST';
export const PRO_BOOKING_COMPLETE_SUCCESS = 'PRO_BOOKING_COMPLETE_SUCCESS';
export const PRO_BOOKING_COMPLETE_FAILED = 'PRO_BOOKING_COMPLETE_FAILED';
export const PRO_BOOKING_COMPLETE_CLEAR = 'PRO_BOOKING_COMPLETE_CLEAR';

export const GET_BOOKING_SLOTS_REQUEST = 'GET_BOOKING_SLOTS_REQUEST';
export const GET_BOOKING_SLOTS_SUCCESS = 'GET_BOOKING_SLOTS_SUCCESS';
export const GET_BOOKING_SLOTS_FAILED = 'GET_BOOKING_SLOTS_FAILED';
export const GET_BOOKING_SLOTS_CLEAR = 'GET_BOOKING_SLOTS_CLEAR';

export const PRO_TRIAL_EXPIRE_CHECK_REQUEST = 'PRO_TRIAL_EXPIRE_CHECK_REQUEST';
export const PRO_TRIAL_EXPIRE_CHECK_SUCCESS = 'PRO_TRIAL_EXPIRE_CHECK_SUCCESS';
export const PRO_TRIAL_EXPIRE_CHECK_FAILED = 'PRO_TRIAL_EXPIRE_CHECK_FAILED';
export const PRO_TRIAL_EXPIRE_CHECK_CLEAR = 'PRO_TRIAL_EXPIRE_CHECK_CLEAR';

export const USER_BOOKING_DETAILS_REQUEST = 'USER_BOOKING_DETAILS_REQUEST';
export const USER_BOOKING_DETAILS_SUCCESS = 'USER_BOOKING_DETAILS_SUCCESS';
export const USER_BOOKING_DETAILS_FAILED = 'USER_BOOKING_DETAILS_FAILED';
export const USER_BOOKING_DETAILS_CLEAR = 'USER_BOOKING_DETAILS_CLEAR';

export const USER_BOOKING_CANCEL_REQUEST = 'USER_BOOKING_CANCEL_REQUEST';
export const USER_BOOKING_CANCEL_SUCCESS = 'USER_BOOKING_CANCEL_SUCCESS';
export const USER_BOOKING_CANCEL_FAILED = 'USER_BOOKING_CANCEL_FAILED';
export const USER_BOOKING_CANCEL_CLEAR = 'USER_BOOKING_CANCEL_CLEAR';

export const USER_BOOKING_RESCHEDULE_REQUEST =
  'USER_BOOKING_RESCHEDULE_REQUEST';
export const USER_BOOKING_RESCHEDULE_SUCCESS =
  'USER_BOOKING_RESCHEDULE_SUCCESS';
export const USER_BOOKING_RESCHEDULE_FAILED = 'USER_BOOKING_RESCHEDULE_FAILED';
export const USER_BOOKING_RESCHEDULE_CLEAR = 'USER_BOOKING_RESCHEDULE_CLEAR';

export const USER_RATING_REVIEW_REQUEST = 'USER_RATING_REVIEW_REQUEST';
export const USER_RATING_REVIEW_SUCCESS = 'USER_RATING_REVIEW_SUCCESS';
export const USER_RATING_REVIEW_FAILED = 'USER_RATING_REVIEW_FAILED';
export const USER_RATING_REVIEW_CLEAR = 'USER_RATING_REVIEW_CLEAR';

export const REFERRAL_CODE_SUCCESS = 'REFERRAL_CODE_SUCCESS';
export const REFERRAL_CODE_CLEAR = 'REFERRAL_CODE_CLEAR';

export const PROFILE_LINK_SUCCESS = 'PROFILE_LINK_SUCCESS';
export const PROFILE_LINK_CLEAR = 'PROFILE_LINK_CLEAR';

export const TRIAL_PLAN_CHANGE_STATUS = 'TRIAL_PLAN_CHANGE_STATUS';

export const ADDITIONAL_REDUCER_CLEAR = 'ADDITIONAL_REDUCER_CLEAR';
export const AUTH_REDUCER_CLEAR = 'AUTH_REDUCER_CLEAR';
export const BOOKING_REDUCER_CLEAR = 'BOOKING_REDUCER_CLEAR';
export const CAT_LIST_REDUCER_CLEAR = 'CAT_LIST_REDUCER_CLEAR';
export const CLIENT_PROFILE_REDUCER_CLEAR = 'CLIENT_PROFILE_REDUCER_CLEAR';
export const CLIENT_LIST_REDUCER_CLEAR = 'CLIENT_LIST_REDUCER_CLEAR';
export const CMS_PAGE_REDUCER_CLEAR = 'CMS_PAGE_REDUCER_CLEAR';
export const FAQ_REDUCER_CLEAR = 'FAQ_REDUCER_CLEAR';
export const PROFESSIONAL_LIST_BY_CAT_REDUCER_CLEAR =
  'PROFESSIONAL_LIST_BY_CAT_REDUCER_CLEAR';
export const PROFESSIONAL_PROFILE_DETAILS_REDUCER_CLEAR =
  'PROFESSIONAL_PROFILE_DETAILS_REDUCER_CLEAR';
export const PROFESSIONAL_PROFILE_SETUP_REDUCER_CLEAR =
  'PROFESSIONAL_PROFILE_SETUP_REDUCER_CLEAR';
export const PROFESSIONAL_SETTING_STEP_REDUCER_CLEAR =
  'PROFESSIONAL_SETTING_STEP_REDUCER_CLEAR';
export const PROFILE_REDUCER_CLEAR = 'PROFILE_REDUCER_CLEAR';
export const REVIEW_REDUCER_CLEAR = 'REVIEW_REDUCER_CLEAR';
export const SIMILER_REDUCER_CLEAR = 'SIMILER_REDUCER_CLEAR';
export const VERIFICATION_REDUCER_CLEAR = 'VERIFICATION_REDUCER_CLEAR';

export const PROFESSIONAL_PROFILE_SETUP_PROGRESSION_UPDATE =
  'PROFESSIONAL_PROFILE_SETUP_PROGRESSION_UPDATE';

export const USER_TYPE_STATUS = 'USER_TYPE_STATUS';

export const ADDITIONAL_CATEGORY_EDIT_REQUEST =
  'ADDITIONAL_CATEGORY_EDIT_REQUEST';
export const ADDITIONAL_CATEGORY_EDIT_SUCCESS =
  'ADDITIONAL_CATEGORY_EDIT_SUCCESS';
export const ADDITIONAL_CATEGORY_EDIT_FAILED =
  'ADDITIONAL_CATEGORY_EDIT_FAILED';
export const ADDITIONAL_CATEGORY_EDIT_CLEAR = 'ADDITIONAL_CATEGORY_EDIT_CLEAR';

export const PROFESSIONAL_FAQ_DELETE_REQUEST =
  'PROFESSIONAL_FAQ_DELETE_REQUEST';
export const PROFESSIONAL_FAQ_DELETE_SUCCESS =
  'PROFESSIONAL_FAQ_DELETE_SUCCESS';
export const PROFESSIONAL_FAQ_DELETE_FAILED = 'PROFESSIONAL_FAQ_DELETE_FAILED';
export const PROFESSIONAL_FAQ_DELETE_CLEAR = 'PROFESSIONAL_FAQ_DELETE_CLEAR';

export const PRO_SETTING_STEP2 = 'PRO_SETTING_STEP2';
export const PRO_SETTING_STEP3 = 'PRO_SETTING_STEP3';
export const PRO_SETTING_DATA_CLEAR = 'PRO_SETTING_DATA_CLEAR';

// Professional Profile Details (Pratik Bose)
export const PROFESSIONAL_PROFILE_DETAILS_REQUEST =
  'PROFESSIONAL_PROFILE_DETAILS_REQUEST';
export const PROFESSIONAL_PROFILE_DETAILS_SUCCESS =
  'PROFESSIONAL_PROFILE_DETAILS_SUCCESS';
export const PROFESSIONAL_PROFILE_DETAILS_FAILED =
  'PROFESSIONAL_PROFILE_DETAILS_FAILED';
export const PROFESSIONAL_PROFILE_DETAILS_CLEAR =
  'PROFESSIONAL_PROFILE_DETAILS_CLEAR';

// Professional Listing by Specific Category (Pratik Bose)
export const PROFESSIONAL_LISTING_BY_CATEGORY_REQUEST =
  'PROFESSIONAL_LISTING_BY_CATEGORY_REQUEST';
export const PROFESSIONAL_LISTING_BY_CATEGORY_SUCCESS =
  'PROFESSIONAL_LISTING_BY_CATEGORY_SUCCESS';
export const PROFESSIONAL_LISTING_BY_CATEGORY_FAILED =
  'PROFESSIONAL_LISTING_BY_CATEGORY_FAILED';
export const PROFESSIONAL_LISTING_BY_CATEGORY_CLEAR =
  'PROFESSIONAL_LISTING_BY_CATEGORY_CLEAR';

// REVIEWS (Pratik Bose)
export const REVIEWS_REQUEST = 'REVIEWS_REQUEST';
export const REVIEWS_SUCCESS = 'REVIEWS_SUCCESS';
export const REVIEWS_FAILED = 'REVIEWS_FAILED';
export const REVIEWS_CLEAR = 'REVIEWS_CLEAR';

export const RATINGS_REQUEST = 'RATINGS_REQUEST';
export const RATINGS_SUCCESS = 'RATINGS_SUCCESS';
export const RATINGS_FAILED = 'RATINGS_FAILED';
export const RATINGS_CLEAR = 'RATINGS_CLEAR';

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILED = 'ADD_TO_CART_FAILED';

export const DELETE_CART_ITEM_REQUEST = 'DELETE_CART_ITEM_REQUEST';
export const DELETE_CART_ITEM_SUCCESS = 'DELETE_CART_ITEM_SUCCESS';
export const DELETE_CART_ITEM_FAILED = 'DELETE_CART_ITEM_FAILED';

export const UPDATE_CART_REQUEST = 'UPDATE_CART_REQUEST';
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS';
export const UPDATE_CART_FAILED = 'UPDATE_CART_FAILED';

export const GET_CART_REQUEST = 'GET_CART_REQUEST';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_FAILED = 'GET_CART_FAILED';

export const BOOK_SERVICE_REQUEST = 'BOOK_SERVICE_REQUEST';
export const BOOK_SERVICE_SUCCESS = 'BOOK_SERVICE_SUCCESS';
export const BOOK_SERVICE_FAILED = 'BOOK_SERVICE_FAILED';
export const BOOK_SERVICE_CLEAR = 'BOOK_SERVICE_CLEAR';

export const SET_BOOKING_EDIT = 'SET_BOOKING_EDIT';

export const SIMILAR_PROS_REQUEST = 'SIMILAR_PROS_REQUEST';
export const SIMILAR_PROS_SUCCESS = 'SIMILAR_PROS_SUCCESS';
export const SIMILAR_PROS_FAILED = 'SIMILAR_PROS_FAILED';
export const SIMILAR_PROS_CLEAR = 'SIMILAR_PROS_CLEAR';

export const SET_CLIENT_LANDING_PAGE = 'SET_CLIENT_LANDING_PAGE';
export const SET_LOCATION_DETAILS = 'SET_LOCATION_DETAILS';

export const STORE_NAVIGATION_ROUTE = 'STORE_NAVIGATION_ROUTE';
export const CLEAR_NAVIGATION_ROUTE = 'CLEAR_NAVIGATION_ROUTE';

// CLIENTS LIST (ANALYTICS SECTION)
export const CLIENTS_LIST_REQUEST = 'CLIENTS_LIST_REQUEST';
export const CLIENTS_LIST_SUCCESS = 'CLIENTS_LIST_SUCCESS';
export const CLIENTS_LIST_FAILED = 'CLIENTS_LIST_FAILED';
export const CLIENTS_LIST_CLEAR = 'CLIENTS_LIST_CLEAR';

export const TOP_CLIENTS_REQUEST = 'TOP_CLIENTS_REQUEST';
export const TOP_CLIENTS_SUCCESS = 'TOP_CLIENTS_SUCCESS';
export const TOP_CLIENTS_FAILED = 'TOP_CLIENTS_FAILED';
export const TOP_CLIENTS_CLEAR = 'TOP_CLIENTS_CLEAR';

export const CLIENT_PROFILE_DETAILS_REQUEST = 'CLIENT_PROFILE_DETAILS_REQUEST';
export const CLIENT_PROFILE_DETAILS_SUCCESS = 'CLIENT_PROFILE_DETAILS_SUCCESS';
export const CLIENT_PROFILE_DETAILS_FAILED = 'CLIENT_PROFILE_DETAILS_FAILED';
export const CLIENT_PROFILE_DETAILS_CLEAR = 'CLIENT_PROFILE_DETAILS_CLEAR';

export const CLIENT_PROFILE_LOADMORE_REQUEST =
  'CLIENT_PROFILE_LOADMORE_REQUEST';
export const CLIENT_PROFILE_LOADMORE_SUCCESS =
  'CLIENT_PROFILE_LOADMORE_SUCCESS';
export const CLIENT_PROFILE_LOADMORE_FAILED = 'CLIENT_PROFILE_LOADMORE_FAILED';
export const CLIENT_PROFILE_LOADMORE_CLEAR = 'CLIENT_PROFILE_LOADMORE_CLEAR';

export const WALKIN_CLIENT_PROFILE_DETAILS_REQUEST =
  'WALKIN_CLIENT_PROFILE_DETAILS_REQUEST';
export const WALKIN_CLIENT_PROFILE_DETAILS_SUCCESS =
  'WALKIN_CLIENT_PROFILE_DETAILS_SUCCESS';
export const WALKIN_CLIENT_PROFILE_DETAILS_FAILED =
  'WALKIN_CLIENT_PROFILE_DETAILS_FAILED';
export const WALKIN_CLIENT_PROFILE_DETAILS_CLEAR =
  'WALKIN_CLIENT_PROFILE_DETAILS_CLEAR';

// ANALYTICS DATA
export const PROFESSIONAL_ANALYTICS_REQUEST = 'PROFESSIONAL_ANALYTICS_REQUEST';
export const PROFESSIONAL_ANALYTICS_SUCCESS = 'PROFESSIONAL_ANALYTICS_SUCCESS';
export const PROFESSIONAL_ANALYTICS_FAILED = 'PROFESSIONAL_ANALYTICS_FAILED';
export const PROFESSIONAL_ANALYTICS_CLEAR = 'PROFESSIONAL_ANALYTICS_CLEAR';

// ANALYTICS GRAPH DATA
export const PROFESSIONAL_ANALYTICS_GRAPHS_REQUEST =
  'PROFESSIONAL_ANALYTICS_GRAPHS_REQUEST';
export const PROFESSIONAL_ANALYTICS_GRAPHS_SUCCESS =
  'PROFESSIONAL_ANALYTICS_GRAPHS_SUCCESS';
export const PROFESSIONAL_ANALYTICS_GRAPHS_FAILED =
  'PROFESSIONAL_ANALYTICS_GRAPHS_FAILED';
export const PROFESSIONAL_ANALYTICS_GRAPHS_CLEAR =
  'PROFESSIONAL_ANALYTICS_GRAPHS_CLEAR';

//CLIENT REVIEWS by PRO (Self)
export const CLIENT_REVIEWS_SELF_REQUEST = 'CLIENT_REVIEWS_SELF_REQUEST';
export const CLIENT_REVIEWS_SELF_SUCCESS = 'CLIENT_REVIEWS_SELF_SUCCESS';
export const CLIENT_REVIEWS_SELF_FAILED = 'CLIENT_REVIEWS_SELF_FAILED';
export const CLIENT_REVIEWS_SELF_CLEAR = 'CLIENT_REVIEWS_SELF_CLEAR';

// CLIENT REVIEWS by PROS (Others)
export const CLIENT_REVIEWS_OTHERS_REQUEST = 'CLIENT_REVIEWS_OTHERS_REQUEST';
export const CLIENT_REVIEWS_OTHERS_SUCCESS = 'CLIENT_REVIEWS_OTHERS_SUCCESS';
export const CLIENT_REVIEWS_OTHERS_FAILED = 'CLIENT_REVIEWS_OTHERS_FAILED';
export const CLIENT_REVIEWS_OTHERS_CLEAR = 'CLIENT_REVIEWS_OTHERS_CLEAR';

export const BLOCK_TIME_REQUEST = 'BLOCK_TIME_REQUEST';
export const BLOCK_TIME_SUCCESS = 'BLOCK_TIME_SUCCESS';
export const BLOCK_TIME_FAILED = 'BLOCK_TIME_FAILED';
export const BLOCK_TIME_CLEAR = 'BLOCK_TIME_CLEAR';

export const USER_OWN_REVIEW_RATING_REQUEST = 'USER_OWN_REVIEW_RATING_REQUEST';
export const USER_OWN_REVIEW_RATING_SUCCESS = 'USER_OWN_REVIEW_RATING_SUCCESS';
export const USER_OWN_REVIEW_RATING_FAILED = 'USER_OWN_REVIEW_RATING_FAILED';
export const USER_OWN_REVIEW_RATING_CLEAR = 'USER_OWN_REVIEW_RATING_CLEAR';

export const GET_CASHFLOW_REQUEST = 'GET_CASHFLOW_REQUEST';
export const GET_CASHFLOW_SUCCESS = 'GET_CASHFLOW_SUCCESS';
export const GET_CASHFLOW_FAILED = 'GET_CASHFLOW_FAILED';

// Manually Add Client Contacts
export const MANUAL_CLIENT_CONTACTS_REQUEST = 'MANUAL_CLIENT_CONTACTS_REQUEST';
export const MANUAL_CLIENT_CONTACTS_SUCCESS = 'MANUAL_CLIENT_CONTACTS_SUCCESS';
export const MANUAL_CLIENT_CONTACTS_FAILED = 'MANUAL_CLIENT_CONTACTS_FAILED';
export const MANUAL_CLIENT_CONTACTS_CLEAR = 'MANUAL_CLIENT_CONTACTS_CLEAR';

export const IMPORT_CLIENT_CONTACTS_REQUEST = 'IMPORT_CLIENT_CONTACTS_REQUEST';
export const IMPORT_CLIENT_CONTACTS_SUCCESS = 'IMPORT_CLIENT_CONTACTS_SUCCESS';
export const IMPORT_CLIENT_CONTACTS_FAILED = 'IMPORT_CLIENT_CONTACTS_FAILED';
export const IMPORT_CLIENT_CONTACTS_CLEAR = 'IMPORT_CLIENT_CONTACTS_CLEAR';
//MESSAGE
export const SET_MESSAGE_DETAILS = 'SET_MESSAGE_DETAILS';
export const CLEAR_MESSAGE_DETAILS = 'CLEAR_MESSAGE_DETAILS';

export const ADD_GROUP_SESSION_REQUEST = 'ADD_GROUP_SESSION_REQUEST';
export const ADD_GROUP_SESSION_SUCCESS = 'ADD_GROUP_SESSION_SUCCESS';
export const ADD_GROUP_SESSION_FAILED = 'ADD_GROUP_SESSION_FAILED';
export const ADD_GROUP_SESSION_CLEAR = 'ADD_GROUP_SESSION_CLEAR';

export const EDIT_GROUP_SESSION_REQUEST = 'EDIT_GROUP_SESSION_REQUEST';
export const EDIT_GROUP_SESSION_SUCCESS = 'EDIT_GROUP_SESSION_SUCCESS';
export const EDIT_GROUP_SESSION_FAILED = 'EDIT_GROUP_SESSION_FAILED';
export const EDIT_GROUP_SESSION_CLEAR = 'EDIT_GROUP_SESSION_CLEAR';

export const REFRESH_BOTTOM_TAB = 'REFRESH_BOTTOM_TAB';
export const SET_INITIAL_NAVIGATION_ROUTE = 'SET_INITIAL_NAVIGATION_ROUTE';
export const CLEAR_INITIAL_NAVIGATION_ROUTE = 'CLEAR_INITIAL_NAVIGATION_ROUTE';

export const STORE_CUSTOM_NAV_FROM_LOGIN = 'STORE_CUSTOM_NAV_FROM_LOGIN';
export const CLEAR_CUSTOM_NAV_FROM_LOGIN = 'CLEAR_CUSTOM_NAV_FROM_LOGIN';
export const TOGGLE_CLIENT_SIGNUP_BACK_BUTTON =
  'TOGGLE_CLIENT_SIGNUP_BACK_BUTTON';

export const IS_LAST_STEP = 'IS_LAST_STEP';

export const INITIAL_STEP = 'INITIAL_STEP';
export const SET_INITIAL_STEP = 'SET_INITIAL_STEP';
